/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;


import DAO.ClienteDao;
import classes.Pessoa;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author geral
 */
public class cadastroCliente extends javax.swing.JFrame {
String nome;
ImageIcon foto;
int acesso;
List<ClienteDao> listaCDao;
    /**
     * Creates new form cadastroCliente
     */
    public cadastroCliente() {
        initComponents();
        lerTabela();
        
    }
    public cadastroCliente(String nome,ImageIcon foto,int acesso) {
        initComponents();
        lerTabela();
        this.nome = nome;
        this.foto = foto;
        this.acesso = acesso;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        labelEndereço = new javax.swing.JLabel();
        labelNomeCliente = new javax.swing.JLabel();
        labelAno = new javax.swing.JLabel();
        labelCpfCliente = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtendereço = new javax.swing.JTextField();
        txtAnoNascimento = new javax.swing.JTextField();
        botaoVoltar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        Tabela = new javax.swing.JScrollPane();
        Dados = new javax.swing.JTable();
        labelTelefone = new javax.swing.JLabel();
        botaoDeletar = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txttelefone = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(244, 208, 106));
        jPanel3.setMinimumSize(new java.awt.Dimension(670, 500));
        jPanel3.setPreferredSize(new java.awt.Dimension(670, 500));

        labelEndereço.setBackground(new java.awt.Color(12, 196, 216));
        labelEndereço.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelEndereço.setForeground(new java.awt.Color(255, 255, 255));
        labelEndereço.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEndereço.setText("Endereço:");
        labelEndereço.setOpaque(true);

        labelNomeCliente.setBackground(new java.awt.Color(12, 196, 216));
        labelNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        labelNomeCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomeCliente.setText("Nome:");
        labelNomeCliente.setOpaque(true);

        labelAno.setBackground(new java.awt.Color(12, 196, 216));
        labelAno.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelAno.setForeground(new java.awt.Color(255, 255, 255));
        labelAno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAno.setText("Ano");
        labelAno.setOpaque(true);

        labelCpfCliente.setBackground(new java.awt.Color(12, 196, 216));
        labelCpfCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelCpfCliente.setForeground(new java.awt.Color(255, 255, 255));
        labelCpfCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCpfCliente.setText("Cpf:");
        labelCpfCliente.setOpaque(true);

        txtnome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtendereço.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtAnoNascimento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAnoNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoNascimentoActionPerformed(evt);
            }
        });

        botaoVoltar.setBackground(new java.awt.Color(255, 71, 71));
        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setBorder(null);
        botaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVoltar.setLabel("voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoCadastrar.setBackground(new java.awt.Color(51, 215, 116));
        botaoCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.setBorder(null);
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        Dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Cpf", "Endereço", "Telefone", "AnoNascimento"
            }
        ));
        Dados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DadosMouseClicked(evt);
            }
        });
        Dados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DadosKeyReleased(evt);
            }
        });
        Tabela.setViewportView(Dados);

        labelTelefone.setBackground(new java.awt.Color(12, 196, 216));
        labelTelefone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        labelTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTelefone.setText("Telefone:");
        labelTelefone.setOpaque(true);

        botaoDeletar.setBackground(new java.awt.Color(51, 215, 116));
        botaoDeletar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoDeletar.setForeground(new java.awt.Color(255, 255, 255));
        botaoDeletar.setText("Deletar");
        botaoDeletar.setBorder(null);
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        botaoAtualizar.setBackground(new java.awt.Color(51, 215, 116));
        botaoAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        botaoAtualizar.setText("Atualizar");
        botaoAtualizar.setBorder(null);
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText(" Cadastro de Clientes");
        jLabel1.setOpaque(true);

        txtCpf.setColumns(11);
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txttelefone.setColumns(13);
        try {
            txttelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(labelNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(labelCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(labelEndereço)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtendereço, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelAno, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(93, 93, 93)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(botaoDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtendereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(txttelefone))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        if(Dados.getSelectedRow() != -1){
            ClienteDao cdao = new ClienteDao();
            ClienteDao c = listaCDao.get(Dados.getSelectedRow());
            
            
            cdao.setidcliente(c.getidcliente());
            cdao.setNome(txtnome.getText());
            cdao.setCpf(txtCpf.getText());
            cdao.setendereco(txtendereço.getText());
            cdao.settelefone(txttelefone.getText());
            cdao.setAnoNascimento(Integer.parseInt(txtAnoNascimento.getText()));

            
            System.out.println(c.getCpf());
            

            txtnome.setText("");
            txtCpf.setText("");
            txtendereço.setText("");
            txttelefone.setText("");
            txtAnoNascimento.setText("");
            
                if(Pessoa.VerificarIdade(cdao.getAnoNascimento())){
                    if (Pessoa.ValidarCPF(cdao.getCpf())){
                        cdao.atualizar(cdao);
                        lerTabela();   
                    }else {
                        JOptionPane.showMessageDialog(null, "Cpf invalido");
                    }
            
                }else {
                    JOptionPane.showMessageDialog(null, "idade invalida");
                }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
        if(Dados.getSelectedRow() != -1){
            ClienteDao cdao = new ClienteDao();
            ClienteDao c = listaCDao.get(Dados.getSelectedRow());
            
            cdao.setidcliente(c.getidcliente());

            txtnome.setText("");
            txtCpf.setText("");
            txtendereço.setText("");
            txttelefone.setText("");
            txtAnoNascimento.setText("");
            
            cdao.deletar(cdao);
            lerTabela();
            
        }else {
            JOptionPane.showMessageDialog(null, "Escolha um cliente para apagar do sistema");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeletarActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        
        ClienteDao cdao = new ClienteDao();
            
        cdao.setNome(txtnome.getText());
        cdao.setCpf(txtCpf.getText());
        cdao.setendereco(txtendereço.getText());
        cdao.settelefone(txttelefone.getText());
        cdao.setAnoNascimento(Integer.parseInt(txtAnoNascimento.getText()));
        
        txtnome.setText("");
        txtCpf.setText("");
        txtendereço.setText("");
        txttelefone.setText("");
        txtAnoNascimento.setText("");

        if(Pessoa.VerificarIdade(cdao.getAnoNascimento())){
            if (Pessoa.ValidarCPF(cdao.getCpf())){
             cdao.adicionar(cdao);
                lerTabela();   
            }else {
                JOptionPane.showMessageDialog(null, "Cpf invalido");
            }
            
        }else {
            JOptionPane.showMessageDialog(null, "idade invalida");
        }



    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
    if (acesso == 1){
                try {
                    new paginaInicialGerente(nome,foto,acesso).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.dispose();
            }else {
                try {
                    new paginaInicial(nome,foto,acesso).setVisible(true);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Erro: "+e);
                }

                this.dispose();
                }
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void txtAnoNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoNascimentoActionPerformed

    private void txttelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefoneActionPerformed

    private void DadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DadosKeyReleased
        verTabela();
    }//GEN-LAST:event_DadosKeyReleased

    private void DadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DadosMouseClicked
        verTabela();
    }//GEN-LAST:event_DadosMouseClicked

    public void lerTabela(){
        DefaultTableModel tabela = (DefaultTableModel) Dados.getModel();
        tabela.setNumRows(0);
        ClienteDao cDao = new ClienteDao();
        listaCDao = cDao.listar();
        
        for (ClienteDao c : listaCDao) {
                tabela.addRow(new Object[]{
                    c.getidcliente(),
                    c.getNome(),
                    c.getCpf(),
                    c.getendereco(),
                    c.gettelefone(),
                    c.getAnoNascimento(),
                });
        }
    }
        private void verTabela(){
        
        if(Dados.getSelectedRow() != -1){
            ClienteDao cDao = listaCDao.get(Dados.getSelectedRow());
            
            txtCpf.setText(cDao.getCpf());
            txtnome.setText(cDao.getNome());
            txtendereço.setText(cDao.getendereco());
            txttelefone.setText(cDao.gettelefone());
            txtAnoNascimento.setText(Integer.toString(cDao.getAnoNascimento()));

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroCliente().setVisible(true);
            }
        });
      
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Dados;
    private javax.swing.JScrollPane Tabela;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelCpfCliente;
    private javax.swing.JLabel labelEndereço;
    private javax.swing.JLabel labelNomeCliente;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JTextField txtAnoNascimento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtendereço;
    private javax.swing.JTextField txtnome;
    private javax.swing.JFormattedTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
