/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import DAO.PetDao;
import classes.Pet;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author geral
 */
public class cadastroPet extends javax.swing.JFrame {
String nome;
ImageIcon foto;
int acesso;
    /**
     * Creates new form cadastroPet
     */
    public cadastroPet() {
        initComponents();
        listarValores();
    }
    
    public cadastroPet(String nome,ImageIcon foto,int acesso) {
        initComponents();
        listarValores();
        
        this.acesso = acesso;
        this.nome = nome;
        this.foto = foto;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomePet = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtIdadePet = new javax.swing.JTextField();
        txtRacaPet = new javax.swing.JTextField();
        voltar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPet = new javax.swing.JTable();
        btnAlterar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel5.setText("Cadastro de Pet");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 110));

        jPanel3.setBackground(new java.awt.Color(244, 208, 106));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(12, 196, 216));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Idade do pet:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 30));

        jLabel1.setBackground(new java.awt.Color(12, 196, 216));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome do Pet:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 30));

        jLabel3.setBackground(new java.awt.Color(12, 196, 216));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Raça:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 30));

        jLabel4.setBackground(new java.awt.Color(12, 196, 216));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ID Cliente:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 30));

        txtNomePet.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel3.add(txtNomePet, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 290, 30));

        txtCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel3.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, 30));

        txtIdadePet.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel3.add(txtIdadePet, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 290, 30));

        txtRacaPet.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel3.add(txtRacaPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 290, 30));

        voltar.setBackground(new java.awt.Color(255, 51, 51));
        voltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        voltar.setBorderPainted(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.setLabel("voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel3.add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 100, 40));

        btnCadastrar.setBackground(new java.awt.Color(51, 215, 116));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 100, 40));

        tabelaPet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Idade", "IdCliente", "Raça"
            }
        ));
        tabelaPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPet);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 570, 150));

        btnAlterar.setBackground(new java.awt.Color(51, 215, 116));
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Atualizar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 100, 40));

        jButton3.setText("Limpar campos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        jLabel6.setBackground(new java.awt.Color(12, 196, 216));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ID do Pet:");
        jLabel6.setMaximumSize(new java.awt.Dimension(36, 16));
        jLabel6.setMinimumSize(new java.awt.Dimension(36, 16));
        jLabel6.setName(""); // NOI18N
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(36, 16));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        txtId.setEnabled(false);
        jPanel3.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, 30));

        btnExcluir.setBackground(new java.awt.Color(51, 215, 116));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Deletar");
        btnExcluir.setMargin(new java.awt.Insets(1, 14, 1, 14));
        btnExcluir.setMaximumSize(new java.awt.Dimension(50, 18));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 100, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 620, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrarPet();
        listarValores();
        limparCampos();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        alterarPet();
        listarValores();
        limparCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        excluirPet();
        listarValores();
        limparCampos();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tabelaPetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPetMouseClicked
      carregarCampos();
    }//GEN-LAST:event_tabelaPetMouseClicked

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        if (acesso == 1){
                try {
                    new paginaInicialGerente(nome,foto,acesso).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.dispose();
            }else {
                try {
                    new paginaInicial(nome,foto,acesso).setVisible(true);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Erro: "+e);
                }

                this.dispose();
                }
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPet;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdadePet;
    private javax.swing.JTextField txtNomePet;
    private javax.swing.JTextField txtRacaPet;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

    private void listarValores() {
        try {
            PetDao objPet = new PetDao();

            DefaultTableModel model = (DefaultTableModel) tabelaPet.getModel();
            model.setNumRows(0);

            ArrayList<Pet> lista = objPet.pesquisarPet();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getIdPet(),
                    lista.get(num).getNomePet(),
                    lista.get(num).getIdadePet(),
                    lista.get(num).getIdCliente(),
                    lista.get(num).getRacaPet()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar valores view: " + erro);
        }
    }
    
    private void limparCampos(){
        txtId.setText("");
        txtNomePet.setText("");
        txtCliente.setText("");
        txtIdadePet.setText("");
        txtRacaPet.setText("");
    }
    
    
    private void cadastrarPet(){
        String nome, idade, raca;
        int idCliente;

        nome = txtNomePet.getText();
        idCliente = Integer.parseInt(txtCliente.getText());
        idade = txtIdadePet.getText();
        raca = txtRacaPet.getText();

        Pet objPet = new Pet();
        objPet.setNomePet(nome);
        objPet.setIdadePet(idade);
        objPet.setIdCliente(idCliente);
        objPet.setRacaPet(raca);

        PetDao objPetDao = new PetDao();
        objPetDao.cadastrarPet(objPet);
    }
    
    private void carregarCampos(){
        int setar = tabelaPet.getSelectedRow();
        txtId.setText(tabelaPet.getModel().getValueAt(setar, 0).toString());
        txtNomePet.setText(tabelaPet.getModel().getValueAt(setar, 1).toString());
        txtIdadePet.setText(tabelaPet.getModel().getValueAt(setar, 2).toString());
        txtCliente.setText(tabelaPet.getModel().getValueAt(setar, 3).toString());
        txtRacaPet.setText(tabelaPet.getModel().getValueAt(setar, 4).toString());
    }
    
    private void alterarPet(){
        int idPet, idCliente;
        String nome, idade, raca;
        
        idPet = Integer.parseInt(txtId.getText());
        nome = txtNomePet.getText();
        idCliente = Integer.parseInt(txtCliente.getText());
        idade = txtIdadePet.getText();
        raca = txtRacaPet.getText();
        
        Pet objPet = new Pet();
        objPet.setIdPet(idPet);
        objPet.setNomePet(nome);
        objPet.setIdadePet(idade);
        objPet.setIdCliente(idCliente);
        objPet.setRacaPet(raca);
        
        PetDao objPetDao = new PetDao();
        objPetDao.alterarPet(objPet);
        
    }
   
    private void excluirPet(){
        int idPet, idCliente;
        String nome, idade, raca;
        
        idPet = Integer.parseInt(txtId.getText());
        nome = txtNomePet.getText();
        idCliente = Integer.parseInt(txtCliente.getText());
        idade = txtIdadePet.getText();
        raca = txtRacaPet.getText();
        
        Pet objPet = new Pet();
        objPet.setIdPet(idPet);
        objPet.setNomePet(nome);
        objPet.setIdadePet(idade);
        objPet.setIdCliente(idCliente);
        objPet.setRacaPet(raca);
        
        PetDao objPetDao = new PetDao();
        objPetDao.excluirPet(objPet);
        
    }

}
