/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import UTIL.Conversao;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author geral
 */
public class paginaInicial extends javax.swing.JFrame {
    Color corFundo = new Color(244,208,106);
    String nome;
    ImageIcon imgF;
    int acesso;

    /**
     * Creates new form paginaInicial
     */
    public paginaInicial() {        
        initComponents();
        getContentPane().setBackground(corFundo);        
    }    
    
    public paginaInicial(String nome, byte[] fotoA,int acesso) throws IOException {
        initComponents();
        getContentPane().setBackground(corFundo);
        
        labelNome.setText("<html><p>" + nome + "</p></html>");
        this.nome = nome;
        imgF = new ImageIcon(fotoA);
        
        imgF.setImage(imgF.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(),Image.SCALE_SMOOTH));
        lblFoto.setIcon(imgF);
        lblFoto.setIcon(imgF);
        
        
    }
    
    public paginaInicial(String nome,ImageIcon foto,int acesso) throws IOException {
        initComponents();
        getContentPane().setBackground(corFundo);
        
        this.acesso = acesso;
        this.nome = nome;
        this.imgF = foto;
        
        imgF.setImage(imgF.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(),Image.SCALE_SMOOTH));
        lblFoto.setIcon(imgF);
        
        labelNome.setText(nome);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cliente = new javax.swing.JButton();
        Pet = new javax.swing.JButton();
        Pedido = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        labelFuncionario = new javax.swing.JLabel();
        lblImgPI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funcionario");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(681, 480));
        setMinimumSize(new java.awt.Dimension(681, 480));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        Cliente.setBackground(new java.awt.Color(12, 196, 216));
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setText("Cadastro Cliente");
        Cliente.setBorder(null);
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(Cliente);
        Cliente.setBounds(20, 138, 176, 35);

        Pet.setBackground(new java.awt.Color(12, 196, 216));
        Pet.setForeground(new java.awt.Color(255, 255, 255));
        Pet.setText("Cadastro Pet");
        Pet.setBorder(null);
        Pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetActionPerformed(evt);
            }
        });
        getContentPane().add(Pet);
        Pet.setBounds(20, 218, 176, 35);

        Pedido.setBackground(new java.awt.Color(12, 196, 216));
        Pedido.setForeground(new java.awt.Color(255, 255, 255));
        Pedido.setText("Entrar Pedido");
        Pedido.setBorder(null);
        Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoActionPerformed(evt);
            }
        });
        getContentPane().add(Pedido);
        Pedido.setBounds(20, 298, 176, 35);

        Sair.setBackground(new java.awt.Color(255, 71, 71));
        Sair.setForeground(new java.awt.Color(255, 255, 255));
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair);
        Sair.setBounds(30, 390, 158, 33);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 120));
        jPanel1.setLayout(null);
        jPanel1.add(labelNome);
        labelNome.setBounds(105, 20, 169, 28);
        jPanel1.add(lblFoto);
        lblFoto.setBounds(6, 4, 81, 110);

        labelFuncionario.setText("Funcionario");
        jPanel1.add(labelFuncionario);
        labelFuncionario.setBounds(105, 54, 80, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 280, 120);
        getContentPane().add(lblImgPI);
        lblImgPI.setBounds(280, 0, 400, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetActionPerformed
        // TODO add your handling code here:
        new cadastroPet(nome, imgF, acesso).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_PetActionPerformed

    private void PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoActionPerformed
        // TODO add your handling code here:
        new entrarPedido(nome,imgF,acesso).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_PedidoActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        // TODO add your handling code here:
        new cadastroCliente(nome, imgF, acesso).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ClienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ImageIcon imgPI = new ImageIcon("src/Interface/imagens/imagemPaginaInicial.jpg");
        imgPI.setImage(imgPI.getImage().getScaledInstance(lblImgPI.getWidth(), lblImgPI.getHeight(), 1));
        lblImgPI.setIcon(imgPI);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paginaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cliente;
    private javax.swing.JButton Pedido;
    private javax.swing.JButton Pet;
    private javax.swing.JButton Sair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFuncionario;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblImgPI;
    // End of variables declaration//GEN-END:variables
}
