/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.Color;
import java.awt.Image;

import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author geral
 */
public class paginaInicialGerente extends javax.swing.JFrame {

    /**
     * Creates new form paginaInicialGerente
     */
    Color corFundo = new Color(244,208,106);
    String nome = null;
    ImageIcon imgF;
    int acesso;
    
    
    public paginaInicialGerente() {
        initComponents();
        getContentPane().setBackground(corFundo);
    }
    
    public paginaInicialGerente(String nome,byte[] fotoA,int acesso) throws IOException {
        initComponents();
        getContentPane().setBackground(corFundo);
        
        this.nome = nome;
        this.acesso = acesso;
        imgF = new ImageIcon(fotoA);
        
        imgF.setImage(imgF.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(),Image.SCALE_SMOOTH));
        lblFoto.setIcon(imgF);
        
        lblNome.setText(nome);
        
        
    }
    
    public paginaInicialGerente(String nome,ImageIcon foto,int acesso) throws IOException {
        initComponents();
        getContentPane().setBackground(corFundo);
        
        this.acesso = acesso;
        this.nome = nome;
        this.imgF = foto;
        
        imgF.setImage(imgF.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(),Image.SCALE_SMOOTH));
        lblFoto.setIcon(imgF);
        
        lblNome.setText(nome);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCliente = new javax.swing.JButton();
        botaoPet = new javax.swing.JButton();
        painelInformacoes = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblGerente = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();
        botaoPedido = new javax.swing.JButton();
        botaoFuncionario = new javax.swing.JButton();
        botaoServico = new javax.swing.JButton();
        lblImgPIG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerente");
        setMaximumSize(new java.awt.Dimension(700, 480));
        setMinimumSize(new java.awt.Dimension(700, 480));
        setPreferredSize(new java.awt.Dimension(681, 480));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        botaoCliente.setBackground(new java.awt.Color(12, 196, 216));
        botaoCliente.setForeground(new java.awt.Color(255, 255, 255));
        botaoCliente.setText("Cadastrar Cliente");
        botaoCliente.setBorder(null);
        botaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCliente);
        botaoCliente.setBounds(20, 150, 176, 35);

        botaoPet.setBackground(new java.awt.Color(12, 196, 216));
        botaoPet.setForeground(new java.awt.Color(255, 255, 255));
        botaoPet.setText("Cadastrar Pet");
        botaoPet.setBorder(null);
        botaoPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPetActionPerformed(evt);
            }
        });
        getContentPane().add(botaoPet);
        botaoPet.setBounds(20, 200, 176, 35);

        painelInformacoes.setBackground(new java.awt.Color(255, 255, 255));
        painelInformacoes.setPreferredSize(new java.awt.Dimension(300, 120));

        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 196, 216), 3));

        lblNome.setText("Default");

        lblGerente.setText("Gerente");

        javax.swing.GroupLayout painelInformacoesLayout = new javax.swing.GroupLayout(painelInformacoes);
        painelInformacoes.setLayout(painelInformacoesLayout);
        painelInformacoesLayout.setHorizontalGroup(
            painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        painelInformacoesLayout.setVerticalGroup(
            painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInformacoesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblNome)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblGerente)
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(painelInformacoesLayout.createSequentialGroup()
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        getContentPane().add(painelInformacoes);
        painelInformacoes.setBounds(0, 0, 280, 130);

        botaoSair.setBackground(new java.awt.Color(255, 71, 71));
        botaoSair.setForeground(new java.awt.Color(255, 255, 255));
        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSair);
        botaoSair.setBounds(28, 405, 158, 33);

        botaoPedido.setBackground(new java.awt.Color(12, 196, 216));
        botaoPedido.setForeground(new java.awt.Color(255, 255, 255));
        botaoPedido.setText("Criar Pedido");
        botaoPedido.setBorder(null);
        botaoPedido.setMaximumSize(new java.awt.Dimension(87, 16));
        botaoPedido.setMinimumSize(new java.awt.Dimension(87, 16));
        botaoPedido.setPreferredSize(new java.awt.Dimension(87, 16));
        botaoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoPedido);
        botaoPedido.setBounds(20, 350, 176, 35);

        botaoFuncionario.setBackground(new java.awt.Color(12, 196, 216));
        botaoFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        botaoFuncionario.setText("Cadastrar Funcionario");
        botaoFuncionario.setBorder(null);
        botaoFuncionario.setMaximumSize(new java.awt.Dimension(87, 16));
        botaoFuncionario.setMinimumSize(new java.awt.Dimension(87, 16));
        botaoFuncionario.setPreferredSize(new java.awt.Dimension(87, 16));
        botaoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(botaoFuncionario);
        botaoFuncionario.setBounds(20, 250, 176, 35);

        botaoServico.setBackground(new java.awt.Color(12, 196, 216));
        botaoServico.setForeground(new java.awt.Color(255, 255, 255));
        botaoServico.setText("Cadastrar Serviço");
        botaoServico.setBorder(null);
        botaoServico.setMaximumSize(new java.awt.Dimension(87, 16));
        botaoServico.setMinimumSize(new java.awt.Dimension(87, 16));
        botaoServico.setPreferredSize(new java.awt.Dimension(87, 16));
        botaoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoServicoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoServico);
        botaoServico.setBounds(20, 300, 176, 35);
        getContentPane().add(lblImgPIG);
        lblImgPIG.setBounds(280, 0, 410, 460);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoClienteActionPerformed
        // TODO add your handling code here:
        new cadastroCliente(nome, imgF, acesso).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botaoClienteActionPerformed

    private void botaoPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPetActionPerformed
        // TODO add your handling code here:
        new cadastroPet(nome, imgF,acesso).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botaoPetActionPerformed

    private void botaoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPedidoActionPerformed
        new entrarPedido(nome, imgF, acesso).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botaoPedidoActionPerformed

    private void botaoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoServicoActionPerformed
        // TODO add your handling code here:
        new cadastroServico(nome, imgF, acesso).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botaoServicoActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFuncionarioActionPerformed
        // TODO add your handling code here:
        new cadastroFuncionario(nome, imgF, acesso).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botaoFuncionarioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ImageIcon imgPG = new ImageIcon("src/Interface/imagens/imagemPaginaInicial.jpg");
        imgPG.setImage(imgPG.getImage().getScaledInstance(lblImgPIG.getWidth(), lblImgPIG.getHeight(), Image.SCALE_SMOOTH));
        
        lblImgPIG.setIcon(imgPG);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paginaInicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paginaInicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paginaInicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paginaInicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paginaInicialGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCliente;
    private javax.swing.JButton botaoFuncionario;
    private javax.swing.JButton botaoPedido;
    private javax.swing.JButton botaoPet;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoServico;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblGerente;
    private javax.swing.JLabel lblImgPIG;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel painelInformacoes;
    // End of variables declaration//GEN-END:variables
}
